services:
  icecast:
    image: ghcr.io/libretime/icecast:2.4.4
    restart: unless-stopped
    ports:
      - "8010:8000"
    environment:
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
      - ICECAST_ADMIN_PASSWORD=${ICECAST_ADMIN_PASSWORD}
      - ICECAST_PASSWORD=${ICECAST_PASSWORD}
      - ICECAST_RELAY_PASSWORD=${ICECAST_RELAY_PASSWORD}
      - ICECAST_HOSTNAME=icecast

  snap-to-icecast-bridge:
    build: .
    container_name: snap_icecast_bridge
    restart: unless-stopped
    depends_on:
      - icecast
    env_file:
      - .env
